/**
 * Provider-private wire types for DeepSeek's Anthropic-compatible Messages API. Citeable
 * result items and citation excerpts arrive in separate blocks; the provider joins them by
 * URL. These types do not create a dependency on `ctx.llm`.
 * @module @deepseek-ai/dsh-web-search-deepseek/types
 */

/** A `web_search_result` item inside a `web_search_tool_result` block. */
export interface WebSearchResultItem {
  type: string
  url: string
  title?: string | null
  /** Provider-supplied page age/recency string (mapped to `publishedAt`). */
  page_age?: string | null
}

/** A `web_search_tool_result` content block: the citeable result shape. */
export interface WebSearchToolResultBlock {
  type: 'web_search_tool_result'
  content?: WebSearchResultItem[]
}

/** One citation location inside a `text` block (the snippet source). */
export interface CitationLocation {
  type?: string
  url?: string | null
  cited_text?: string | null
}

/** A `text` content block: the model's prose plus per-URL citations. */
export interface TextBlock {
  type: 'text'
  text?: string | null
  citations?: CitationLocation[]
}

/** Any content block; only `web_search_tool_result` and `text` are consumed. */
export type ContentBlock = WebSearchToolResultBlock | TextBlock | { type: string }

/** Anthropic Messages usage report (`usage` field of the response envelope). */
export interface AnthropicUsage {
  /** Uncached input tokens billed for the request; cache traffic is reported separately. */
  input_tokens?: number
  /** Input tokens written to the provider cache by this request. */
  cache_creation_input_tokens?: number
  /** Input tokens served from the provider cache by this request. */
  cache_read_input_tokens?: number
  /** Output tokens generated by the model. */
  output_tokens?: number
}

/** DeepSeek's Anthropic Messages response envelope. */
export interface AnthropicResponse {
  content?: ContentBlock[]
  usage?: AnthropicUsage
}

/** DeepSeek's error response envelope (best-effort; fields vary). */
export interface AnthropicError {
  error?: { message?: string } | string
  message?: string
}
